services:
  mysql-notification:
    container_name: mysql-notification
    image: mysql
    environment:
      MYSQL_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: notification_service
      MYSQL_USER: zingmp3
      MYSQL_PASSWORD: zingmp3
      MYSQL_TCP_PORT: 3339
    volumes:
      - ./database/notification_service:/data/mysql
    ports:
      - "3339:3339"
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
    networks:
      zingmp3-net:
networks:
  zingmp3-net:
    name: zingmp3-net