version: '3.8'
services:

  ### MySQL playlist service
  mysql-playlist:
    container_name: mysql-playlist
    image: mysql
    environment:
      MYSQL_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: playlist_service
      MYSQL_USER: zingmp3
      MYSQL_PASSWORD: zingmp3
      MYSQL_TCP_PORT: 3308
    volumes:
      - ./database/mysql-playlist:/data/mysql
    ports:
      - "3308:3308"
    restart: always
    networks:
      - zingmp3-net
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]

  ### MySQL content delivery service

networks:
  zingmp3-net:
    name: zingmp3-net