version: '3.8'
services:
  mysql-playlist:
    container_name: mysql-playlist
    image: mysql
    environment:
      MYSQL_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: playlist_service
      MYSQL_USER: zingmp3
      MYSQL_PASSWORD: zingmp3
      MYSQL_TCP_PORT: 3308
    volumes:
      - ./database/mysql-playlist:/data/mysql
    ports:
      - "3308:3308"
    restart: always
    networks:
      - zingmp3-net
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]

  mysql-playback:
    container_name: mysql-playback
    image: mysql
    environment:
      MYSQL_ROOT_HOSTS: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: playback_service
      MYSQL_USER: zingmp3
      MYSQL_PASSWORD: zingmp3
      MYSQL_TCP_PORT: 3310
    restart: always
    ports:
      - "3310:3310"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
    networks:
      - zingmp3-net
networks:
  zingmp3-net:
    name: zingmp3-net