version: '3.8'
services:
  ## Keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.3
    command: [ "start-dev", "--import-realm" ]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL_HOST: mysql-keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_PORT: 3307
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak-secret
    ports:
      - "8080:8080"
    depends_on:
      mysql-keycloak:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
    networks:
      - zingmp3-net

  ## mysql-keycloak
  mysql-keycloak:
    container_name: mysql-keycloak
    image: mysql
    environment:
      MYSQL_ROOT_HOSTS: '%'
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak-secret
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3307"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
    networks:
      - zingmp3-net
    volumes:
      - ./database/mysql-keycloak:/var/lib/mysql
networks:
  zingmp3-net:
    name: zingmp3-net