eureka:
  client:
    service-url:
      default-zone: http://discovery-service:8761/eureka
server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/zing-mp3