spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER-URI:http://localhost:8080/realms/zing-mp3}
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**, /v3/api-docs/user-service/**, /api/register/**
        - id: auth-service
          uri: ${KEYCLOAK_OPENID-CONNECT:http://localhost:8080/realms/zing-mp3/protocol/openid-connect/}
          predicates:
            - Path=/api/auth/**, /v3/api-docs/auth-service/**
          filters:
            - RewritePath=/api/auth/?(?<segment>), /realms/zing-mp3/protocol/openid-connect/$\{segment}
        - id: content-delivery-service
          uri: lb://content-delivery-service
          predicates:
              - Path=/api/content-delivery/**, /v3/api-docs/content-delivery/**, /images/**
        - id: playlist-service
          uri: lb://playlist-service
          predicates:
            - Path=/api/playlist/**, /v3/api-docs/playlist-service/**
        - id: music-service
          uri: lb://music-service
          predicates:
            - Path=/api/music/**, /v3/api-docs/music-service/**
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE-URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
logging:
  level:
    root: info
    org:
      springframework:
        cloud.gateway: info
        http.server.reactive: info
        web.reactive: info
#    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info
#    org.springframework.cloud.gateway: info
server:
  port: 8081
  host: ${SERVER_HOST:localhost:8081}
springdoc:
  swagger-ui:
    enabled: true
    oauth:
      client-id: user-service
      client-secret: jSLIfcd5eq2t6e0CzNid3QKUaQNP1m0x
    operations-sorter: method
    tags-sorter: alpha
#    urls:
#      - name: auth-service
#        url: /v3/api-docs/auth-service
#      - name: song-service
#        url: /v3/api-docs/song-service
#      - name: user-service
#        url: /v3/api-docs/user-service
#      - name: playlist-service
#        url: /v3/api-docs/playlist-service

