eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.1.21:8080/realms/zing-mp3

logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: info
    springframework.cloud.gateway: trace