services:
  mysql-playlist:
    container_name: mysql-playlist
    image: mysql
    environment:
      MYSQL_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: playlist_service
      MYSQL_USER: zingmp3
      MYSQL_PASSWORD: zingmp3
      MYSQL_TCP_PORT: 3338
    volumes:
      - ./database/playlist_service:/data/mysql
    ports:
      - "3338:3338"
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
    networks:
      zingmp3-net:
networks:
  zingmp3-net:
    name: zingmp3-net