version: '3.8'
services:
  mysql-playback:
    container_name: mysql-playback
    image: mysql
    environment:
      MYSQL_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: content_delivery
      MYSQL_USER: zingmp3
      MYSQL_PASSWORD: zingmp3
      MYSQL_TCP_PORT: 3310
    volumes:
      - ../database/mysql-playback-service:/data/mysql
    ports:
      - "3310:3310"
    restart: always
    networks:
      zingmp3-net:
networks:
  zingmp3-net:
    name: zingmp3-net