spring:
  datasource:
    driver-class-name: ${JDBC_DATABASE_DRIVER:}
    url: ${JDBC_DATABASE_URL:}
    username: ${JDBC_DATABASE_USERNAME:}
    password: ${JDBC_DATABASE_PASSWORD:}
  application:
    name: user-service
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:}
server:
  port: 0
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:}

