spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${spring.datasource.server}:${spring.datasource.port}/${spring.datasource.name}
    username: ${SPRING_DATASOURCE_USERNAME:zingmp3}
    password: ${SPRING_DATASOURCE_PASSWORD:zingmp3}
    server: ${SPRING_DATASOURCE_SERVER:localhost}
    port: ${SPRING_DATASOURCE_PORT:3340}
    name: ${SPRING_DATASOURCE_NAME:user_service}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/zing-mp3}
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092,localhost:9093,localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: ${SERVER_PORT:0}
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:${EUREKA_PORT:8761}/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
#    ip-address: ${HOST_IP:localhost}
keycloak:
  realm: zing-mp3
  client-id: user-service
  resource-id: user-service
  client-secret: ${KEYCLOAK_CLIENT_SECRET:jSLIfcd5eq2t6e0CzNid3QKUaQNP1m0x}
  urls:
    auth: ${KEYCLOAK_URLS_AUTH:http://localhost:8080}
  token-url: ${KEYCLOAK_TOKEN:http://localhost:8080/api/auth/token}
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    deep-linking: true
    oauth:
      client-id: ${KEYCLOAK_CLIENT_ID:user-service}
      client-secret: ${KEYCLOAK_CLIENT_SECRET:jSLIfcd5eq2t6e0CzNid3QKUaQNP1m0x}
grpc:
  client:
    image-service:
      address: discovery:///image-service
      negotiation-type: plaintext
  server:
    port: ${SERVER_GRPC_PORT:0}
