spring:
  application:
    name: user-service
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: user-service
            client-secret: jSLIfcd5eq2t6e0CzNid3QKUaQNP1m0x
      resourceserver:
        jwt:
          issuer-uri: http:///keycloak:8080/realms/zing-mp3
server:
  port: 8083
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.21
  client:
    service-url:
      default-zone: http://discovery-service:8761/eureka
keycloak:
  domain: keycloak
  realm: zing-mp3
  client-id: user-service
  client-secret: jSLIfcd5eq2t6e0CzNid3QKUaQNP1m0x
  urls:
    auth: http://${keycloak.domain}:8080
  token-url: http://nxc-hcmus.me:8081/api/auth/token
  resource-id: user-service
springdoc:
  swagger-ui:
    oauth:
      client-id: ${keycloak.client-id}
      client-secret: ${keycloak.client-secret}
    operations-sorter: method
    tags-sorter: alpha