spring:
  application:
    name: discovery-service
server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    fetch-registry: false

management.endpoint.health.enabled: true
management.endpoints.web.exposure.include: "health"
logging:
  level:
    com.netflix.discovery: "OFF"
    com.netflix.eureka: "OFF"
