spring:
  application:
    name: discovery-service
server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
#    ip-address: ${HOST_IP:localhost}
  client:
    register-with-eureka: false
    healthcheck:
      enabled: true
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVICE-URL:http://localhost:8761/eureka/}
  server:
    enable-self-preservation: false
