services:
  mysql-audio:
    container_name: mysql-audio
    image: mysql
    environment:
      MYSQL_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: audio_service
      MYSQL_USER: zingmp3
      MYSQL_PASSWORD: zingmp3
      MYSQL_TCP_PORT: 3334
    volumes:
      - ../database/audio_service:/data/mysql
    ports:
      - "3334:3334"
    restart: always
    networks:
      zingmp3-net:
networks:
  zingmp3-net:
    name: zingmp3-net