spring:
  application:
    name: playlist-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${spring.datasource.server}:${spring.datasource.port}/${spring.datasource.name}
    username: ${SPRING_DATASOURCE_USERNAME:zingmp3}
    password: ${SPRING_DATASOURCE_PASSWORD:zingmp3}
    server: ${SPRING_DATASOURCE_SERVER:localhost}
    port: ${SPRING_DATASOURCE_PORT:3308}
    name: ${SPRING_DATASOURCE_NAME:playlist_service}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER-URI:http://localhost:8080/realms/zing-mp3}
  codec:
    max-in-memory-size: 1GB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: ${SERVER_PORT:8080}
  host: ${SERVER_HOST:localhost:8081}
  url: ${SERVER_URL:http://localhost:8081}
springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
#logging:
#  level:
#    root: debug
grpc:
  client:
    music:
      address: static://localhost:9001
      negotiation-type: plaintext
  server:
    port: 9000

