spring:
  application:
    name: artist-service
  datasource:
    url: jdbc:mysql://localhost:3309/artist_service?createDatabaseIfNotExist=true
    username: zingmp3
    password: zingmp3
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    use-root-path: true
server:
  port: 8081
  http2:
    enabled: true
application:
  version: 1.0

