services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    restart: always
    ports:
    - 8000:8080
    - 50000:50000
    container_name: jenkins
    volumes:
      - /home/nxc/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock