spring:
  datasource:
    url: jdbc:mysql://mysql-song:3306/song_service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/zing-mp3
#grpc:
#  server:
#    port: 0
server:
  port: 8082
eureka:
  client:
    service-url:
      default-zone: http://discovery-service:8761/eureka
springdoc:
  swagger-ui:
    oauth:
      client-id: song-service
      client-secret: ghohHM6oyyOcGTZzyTC8Lyxh713XAKhg

keycloak:
  tokenUrl: http://nxc-hcmus.me:8081/api/auth/token
