version: '3.9'
services:
  mysql-artist:
    container_name: mysql-artist
    image: mysql
    environment:
      MYSQL_ROOT_HOSTS: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: artist_service
      MYSQL_USER: zingmp3
      MYSQL_PASSWORD: zingmp3
      MYSQL_TCP_PORT: 3309
    ports:
      - "3309:3309"
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
    networks:
      - zingmp3-net

networks:
  zingmp3-net:
    name: zingmp3-net
