services:
  mysql-user:
    container_name: mysql-user
    image: mysql
    environment:
      MYSQL_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_service
      MYSQL_USER: zingmp3
      MYSQL_PASSWORD: zingmp3
      MYSQL_TCP_PORT: 3340
    volumes:
      - ./database/user_service:/data/mysql
    ports:
      - "3340:3340"
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
    networks:
      zingmp3-net:
networks:
  zingmp3-net:
    name: zingmp3-net