version: '3.8'
services:
  mysql-music:
    container_name: mysql-music
    image: mysql
    environment:
      MYSQL_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: music_service
      MYSQL_USER: zingmp3
      MYSQL_PASSWORD: zingmp3
      MYSQL_TCP_PORT: 3309
    volumes:
      - ../database/mysql-music-service:/data/mysql
    ports:
      - "3309:3309"
    restart: always
    networks:
      zingmp3-net:
networks:
  zingmp3-net:
    name: zingmp3-net