spring:
  application:
    name: artist-core
  datasource:
    url: jdbc:mysql://${spring.datasource.server}:${spring.datasource.port}/${spring.datasource.name}
    username: ${SPRING_DATASOURCE_USERNAME:zingmp3}
    password: ${SPRING_DATASOURCE_PASSWORD:zingmp3}
    server: ${SPRING_DATASOURCE_SERVER:localhost}
    port: ${SPRING_DATASOURCE_PORT:3336}
    name: ${SPRING_DATASOURCE_NAME:artist_service}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER-URI:http://localhost:8080/realms/zing-mp3}
#      client:
#        registration:
#          keycloak:
#            client-id: ${KEYCLOAK_CLIENT_ID:music-service}
#            client-secret: ${KEYCLOAK_CLIENT_SECRET:VkkYcgHZEnyEbKNBr0Ca1uit4i1iORz7}
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092,localhost:9093,localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    deep-linking: true
    oauth:
      client-id: ${KEYCLOAK_CLIENT_ID:music-service}
      client-secret: ${KEYCLOAK_CLIENT_SECRET:VkkYcgHZEnyEbKNBr0Ca1uit4i1iORz7}
server:
  port: ${SERVER_PORT:0}
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:${EUREKA_PORT:8761}/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
#    ip-address: ${HOST_IP:localhost}
grpc:
  client:
    image-service:
      address: discovery:///image-service
      negotiation-type: plaintext
  server:
    port: ${GRPC_SERVER_PORT:0}
kafka:
  topic:
    name: ${KAFKA_TOPIC:artist-service}
management:
  endpoint:
    health:
      show-details: never
keycloak:
  resource-id: "music-service"
  token-url: ${KEYCLOAK_TOKEN:http://localhost:8080/auth/realms/zing-mp3/protocol/openid-connect/token}