services:
  mysql-search:
    container_name: mysql-search
    image: mysql
    environment:
      MYSQL_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: search_service
      MYSQL_USER: zingmp3
      MYSQL_PASSWORD: zingmp3
      MYSQL_TCP_PORT: 3341
    volumes:
      - ./database/search_service:/data/mysql
    ports:
      - "3341:3341"
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
    networks:
      zingmp3-net:
networks:
  zingmp3-net:
    name: zingmp3-net