spring:
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
    username: zingmp3
    password: zingmp3
    driverClassName: org.h2.Driver
  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
eureka:
  client:
    enabled: false