server:
  port: 0
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music_service
    username: zingmp3
    password: zingmp3
  application:
    name: music-service

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/
#  instance:
#    prefer-ip-address: true